using Microsoft.EntityFrameworkCore;

namespace GlowBook.Web.Data;

public static class PostgresSchemaPatcher
{
    public const string MiniSiteMigrationId = "20261002213638_MiniSiteCalendarColors";

    public static async Task ApplyAsync(ApplicationDbContext db, ILogger logger)
    {
        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "Services" ADD COLUMN IF NOT EXISTS "Color" character varying(7);
            ALTER TABLE "MasterProfiles" ADD COLUMN IF NOT EXISTS "PageAccentColor" character varying(7);
            ALTER TABLE "MasterProfiles" ADD COLUMN IF NOT EXISTS "ShowOnMap" boolean NOT NULL DEFAULT TRUE;
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "MasterPortfolioPhotos" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "MasterProfileId" integer NOT NULL,
                "Data" bytea NOT NULL,
                "ContentType" character varying(100) NOT NULL,
                "Caption" character varying(200),
                "SortOrder" integer NOT NULL,
                "CreatedAt" timestamp without time zone NOT NULL,
                CONSTRAINT "FK_MasterPortfolioPhotos_MasterProfiles_MasterProfileId"
                    FOREIGN KEY ("MasterProfileId") REFERENCES "MasterProfiles" ("Id") ON DELETE CASCADE
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "MasterPromos" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "MasterProfileId" integer NOT NULL,
                "Title" character varying(120) NOT NULL,
                "Description" character varying(500),
                "Badge" character varying(40),
                "ValidUntil" timestamp without time zone,
                "IsActive" boolean NOT NULL,
                "CreatedAt" timestamp without time zone NOT NULL,
                CONSTRAINT "FK_MasterPromos_MasterProfiles_MasterProfileId"
                    FOREIGN KEY ("MasterProfileId") REFERENCES "MasterProfiles" ("Id") ON DELETE CASCADE
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "MasterReviews" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "MasterProfileId" integer NOT NULL,
                "ClientId" integer,
                "AuthorName" character varying(80) NOT NULL,
                "AuthorPhone" character varying(30) NOT NULL,
                "Rating" integer NOT NULL,
                "Text" character varying(800) NOT NULL,
                "IsPublished" boolean NOT NULL,
                "CreatedAt" timestamp without time zone NOT NULL,
                CONSTRAINT "FK_MasterReviews_Clients_ClientId"
                    FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE SET NULL,
                CONSTRAINT "FK_MasterReviews_MasterProfiles_MasterProfileId"
                    FOREIGN KEY ("MasterProfileId") REFERENCES "MasterProfiles" ("Id") ON DELETE CASCADE
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_MasterPortfolioPhotos_MasterProfileId_SortOrder"
                ON "MasterPortfolioPhotos" ("MasterProfileId", "SortOrder");
            CREATE INDEX IF NOT EXISTS "IX_MasterPromos_MasterProfileId_IsActive"
                ON "MasterPromos" ("MasterProfileId", "IsActive");
            CREATE INDEX IF NOT EXISTS "IX_MasterReviews_ClientId"
                ON "MasterReviews" ("ClientId");
            CREATE INDEX IF NOT EXISTS "IX_MasterReviews_MasterProfileId_IsPublished_CreatedAt"
                ON "MasterReviews" ("MasterProfileId", "IsPublished", "CreatedAt");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
            SELECT {0}, '8.0.8'
            WHERE EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = '__EFMigrationsHistory')
              AND NOT EXISTS (
                  SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = {0}
              );
            """, MiniSiteMigrationId);

        logger.LogInformation("Postgres mini-site schema patch applied");
    }
}
